# Generated by Django 4.1.1 on 2023-01-23 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="featured",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="whether the book should be featured on the home page",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(
                blank=True, default="", help_text="description text written in markdown"
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="renewal_date",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                help_text="date the loan was last renewed (or first began if it has never been renewed)",
            ),
        ),
    ]
