# Generated by Django 4.1.1 on 2023-01-26 22:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_book_featured_alter_book_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="featured",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="whether the book should be featured on the home page - make sure it has a cover",
            ),
        ),
    ]
