# Generated by Django 4.1.1 on 2023-01-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_book_created_alter_book_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="off_shelves",
            field=models.BooleanField(
                default=False,
                help_text="whether the book has been removed from the shelves and placed in the reserved section",
            ),
        ),
    ]
