# Generated by Django 4.1.1 on 2023-01-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_reservation_off_shelves"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="copy",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservation",
                to="lms.bookcopy",
            ),
        ),
    ]
