# Generated by Django 4.1.1 on 2023-01-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_remove_reservation_created_reservation_ready"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="off_shelves",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="whether the book has been taken off the shelves and put in the reserved section",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="ready",
            field=models.DateField(
                blank=True,
                help_text="date the reservation was ready for collection ",
                null=True,
            ),
        ),
    ]
