# Generated by Django 4.1.1 on 2023-01-27 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_alter_reservation_off_shelves_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="ready",
            new_name="ready_since",
        ),
    ]
