# Generated by Django 4.1.1 on 2023-03-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0010_rename_ready_reservation_ready_since"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="libraryuser",
            name="loan_length",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=7,
                help_text="number of days that each loan/renewal the user makes is valid for",
            ),
        ),
    ]
