# Generated by Django 4.2.2 on 2023-09-05 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0011_alter_book_options_alter_libraryuser_loan_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historyloan",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_history",
                to="lms.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="historyloan",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
